baseURL: http://tylerwcs.github.io/blog/
title: CS's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
    category: categories
    tag: tags
    
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: CS Blog
  description: "Place to showcase projects"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # home-info mode
  homeInfoParams:
    Title: "Work Hard Play Hard \U0001F4AA"
    Content: Welcome to my blog! This is a place where I blog my projects and walkthroughs that I have done. 

  socialIcons: # optional
         - name: github
           url: "https://github.com/tylerwcs"
         - name: linkedin
           url: "https://www.linkedin.com/in/wong-cai-shen-481560223/"
         - name: phone
           url: "https://wa.me/601156780046"
         - name: cv
           url: "https://www.linkedin.com/in/wong-cai-shen-481560223/"


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
# baseURL: http://tylerwcs.github.io/blog/
# languageCode: en-us
# title: My New Hugo Site
# theme: "PaperMod"

# params:
#     homeInfoParams:
#         Title: Hi there \U0001F44B
#         Content: Welcome to my Blog!

#     socialIcons: # optional
#         - name: github
#           url: "https://github.com/tylerwcs"
#         - name: linkedin
#           url: "https://www.linkedin.com/in/wong-cai-shen-481560223/"